### PR TITLE
Fix RssFeed page for jekyll 3.4.3

### PR DESCRIPTION
**Pull request by dacap**
Fixes a problem using jekyll 3.4.3:

    Error reading file /home/user/myblog/public_html/rss.xml: No such file or directory @ rb_sysopen - /home/user/myblog/workdir/home/user/myblog/public_html/rss.xml

I didn't test this patch with old versions of jekyll.

### CODE REVIEW

**Comment by dacap** [comment]
It looks like this fixed the error but the `rss.xml` file is empty 😭

**Comment by assafgelber** [comment]
Wow, I haven't maintained this repo for years 😅

Let me see if I can play around with it and get it working again. Thanks!

**Comment by dacap** [comment]
Hi @assafgelber, don't worry, actually I've used https://github.com/snaptortoise/jekyll-rss-feeds because it uses a template to create the RSS instead of a plugin (which might be better for GitHub pages too). As a side note I'm giving the RSS alternative only for backward compatibility with a program that consumed the RSS from a migrated Tumblr blog to Jekyll.

**Comment by Merovius** [comment]
I believe this is supposed to fix the same issue as #17. From what I can tell, that one actually works, though :)

**Comment by assafgelber** [comment]
Closing this since #17, should take care of this. Let me know if this is not the case!

**Pull request closed without merging**
